apiVersion: 2021-10-01
location: southafricanorth
name: cg-cloudxeus-app-mysql
properties:
  containers:
    - name: cloudxeus-app
      properties:
        image: regevsan100.azurecr.io/cloudxeus-app:v1
        resources:
          requests:
            cpu: 1
            memoryInGB: 1.5
        ports:
          - port: 80
        environmentVariables:
          - name: ASPNETCORE_URLS
            value: http://+:80

    - name: cloudxeus-mysql
      properties:
        image: regevsan100.azurecr.io/cloudxeus-mysql:8.4
        resources:
          requests:
            cpu: 1
            memoryInGB: 2
        ports:
          - port: 3306
        environmentVariables:
          - name: MYSQL_ROOT_PASSWORD
            value: Microsoft@2026

  osType: Linux

  ipAddress:
    type: Public
    ports:
      - protocol: tcp
        port: 80

  imageRegistryCredentials:
    - server: regevsan100.azurecr.io
      username: regevsan100
      password: AnSjbUCkWnfFO27Ru7teUB1pfUhhkq5qefzhAazHXgQPzCwqtE99JQQJ99CDACrIdLPEqg7NAAACAZCRkbxz

  restartPolicy: Always
type: Microsoft.ContainerInstance/containerGroups
